-- AlterTable
ALTER TABLE "ProductImage" ADD COLUMN     "boyutBayt" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "genislik" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "kucukYol" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "olusturuldu" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "yukseklik" INTEGER NOT NULL DEFAULT 0;
